### ISSUE TITLE
Unable to press Offer button after filling in form

### ISSUE THREAD

**Issue by Rivmedia** [angelleye/offers-for-woocommerce#406] opened 2018-12-21 13:48 UTC
I've tried with a few pre-made templates and also our custom theme,  but I can only seem to get the button working when using twenty twelve. 

No php errors,  no console errors.  Just won't submit an offer.   Have you experienced this before, please advise :)

Example URL: https://www.thinkbrands.co.uk/names/asteriodmining-co-uk

**Comment by iMansoorAliKhan** [comment] 2018-12-21 16:01
Hi @Rivmedia This seems to be a conflict of some sort as we are not getting any reports of this sort nor we are able to reproduce that.  So can you please try the following debug steps:

1. Check your site's PHP version and make sure that it is 5.6 or above
2. Disable all plugins with the exception of WooCommerce and Offers  for WooCommerce, and determine whether or not the issue is still occurring
3. Re-enable additional plugins one by one, testing after each add-on is enabled, in order to find the culprit

If, after disabling all additional plugins, you are still seeing the same issue, then switch to basic twenty theme with both WooCommerce and Offers for WooCommerce enabled and then check once again.

Please follow these steps and let us know your results.

Thank you!

**Comment by Rivmedia** [comment] 2018-12-21 17:18
I think it could be an incompatibility with Elementor,  unfortunately Elementor is something we want to use. 

I have found an error when editing elementor templates in regards to this plugin,  but i don't think it would have an effect on front end submission ?  I think its possibly because the template is essentially allowing a fake view of the single product page and therefore offers isn't able to display ?  

`

1. | Angelleye_Offers_For_Woocommerce->angelleye_ofwc_lightbox_make_offer_form('')/home/thinkbrandsco/public_html/wp-includes/class-wp-hook.php:286
-- | --
2. | WP_Hook->apply_filters(NULL, Array)/home/thinkbrandsco/public_html/wp-includes/class-wp-hook.php:310
3. | WP_Hook->do_action(Array)/home/thinkbrandsco/public_html/wp-includes/plugin.php:453
4. | do_action('woocommerce_bef...')/home/thinkbrandsco/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/documents/product.php:152
5. | ElementorPro\Modules\Woocommerce\Documents\Product->print_content()/home/thinkbrandsco/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php:218
6. | ElementorPro  in  /home/thinkbrandsco/public_html/wp-content/plugins/offers-for-woocommerce/public/class-offers-for-woocommerce.php  on line 452/home/thinkbrandsco/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php:171

`

**Comment by iMansoorAliKhan** [comment] 2018-12-21 17:53
Well there should  not be an error like that unless there is some conflict coming from a plugin or theme . Did you tried the basic debugging and are able to find any other culprits other than elementor? We can certainly try with that but we don't be due to a number of reasons.
- Not very much users are on elementor.
- Our plugin works on woo product which is not relating to elementor
- We haven't get a chance to test plugin working with that 

Based on that it would be difficult to say what's going on there.
So, it would be great if you are able to run some test as suggested above and let me know what you got.

Thanks!

**Comment by angelleye** [comment] 2019-01-14 00:02
@iMansoorAliKhan Did you create a ticket about this in our Jira project?  Have you attempted to reproduce this problem with Elementor?

**Comment by iMansoorAliKhan** [comment] 2019-01-14 16:17
@angelleye  I did installed elementor and elementor pro, but I dont know how I can reproduce the error. I believe their theme might be giving support for custom call to actions button . And no, this is not yet moved to Jira.

**Comment by Rivmedia** [comment] 2019-01-14 16:23
Just for the record,  It has nothing to do with our theme.  

It's irrelevant for us now as we've not used the plugin and as a result and built a better system,  but your lack of knowledge of Elementor shouldn't enable you to pass blame.  There is over a million installs of Elementor and is considered to be the best page builder wordpress has to offer,  discounting it's usage and stating "not very much users are on Elementor" is an indication that you didnt really look into the problem and that's why I didnt bother following up to your reply.

**Comment by iMansoorAliKhan** [comment] 2019-01-14 16:38
@Rivmedia I didn't mean to put a blame on anything. All I need to know is steps to reproduce  the error with elementor and we will be happy to run some further tests to see what's going on there.

So can you please help me reproduce this error which you are reporting?

**Comment by Rivmedia** [comment] 2019-01-14 16:46
Without going into massive detail.  You need to create a global page template,  so the design/template is applied to all pages.  On that global template include your shortcode. 

https://docs.elementor.com/article/359-creating-a-single-page-template-with-elementor-pro

So "Elementor templates -  create page template - Set conditions" 

This will setup elementor to show that design and your shortcode on all pages defined in the conditions.  

From that point on, after its saved you will find that the template no longer loads on the backend ( unless you disable your plugin ) and you will also find that the offer button can not be pressed on the frontend. 

I'm afraid I can't help more than that, because as I explained we no longer use that plugin to accomplish our goal,  we used a combination of Gravity forms and Stripe gateway instead.

**Comment by iMansoorAliKhan** [comment] 2019-01-21 08:33
Hi @Rivmedia ,

Thanks for your feedback, we will look into that, try to reproduce it and if we got a success reproducing that, then will definitely going to make adjustments. I still have one last question. Offers for woocommerce don't offer any shortcodes so I'm confused about when you said **add your shortcode**, which shortcode?

**Comment by angelleye** [comment] 2019-02-05 03:41
@Rivmedia Thanks for the feedback here.  We have resolved this issue and it will be fixed in our next update if you want to give it another try.  I can tell you that not including PayPal as an option on your site will definitely result in lost sales.  

Thanks again for the feedback, and keep your eye out for the update if you want to give it another try.

**Closed by angelleye** 2019-02-05 03:41 UTC
