### ISSUE TITLE
Error Submitting Offer

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#312] opened 2017-06-05 04:05 UTC
Hi @tejasm-itpath 

Please take a look at the following ticket. the customer is getting following error when they are not login to the site. so, in short, a general visitor is getting following error though the offer is sent and shows in the admin side.

> **= Error: There was an error sending your offer, please try again. If this problem persists, please contact us.**
**Screenshot:** 
![image](https://cloud.githubusercontent.com/assets/11312949/26770085/3e8df99e-49cd-11e7-89bf-3a6cb41205cf.png)
**Debug Params screen:**

![img_05062017_085222_0](https://cloud.githubusercontent.com/assets/11312949/26770160/b31ac4fe-49cd-11e7-916f-7ce262dda015.png)

when I m login to the site: tested as admin
the offer is sent succesfully.

**Comment by tejasm-itpath** [comment] 2017-06-05 06:18
@MansoorAliKhanOfficial  
Can you tell me about the version of the WooCommerce and Offers for Woocommerce plugins ?

**Comment by tejasm-itpath** [comment] 2017-06-05 06:40
@angelleye  @MansoorAliKhanOfficial  
I am running version **1.4.6 for Offers For Woo-commerce and Version 3.0.7 For WooCommerce** .
I can not reproduce this error.
If possible then, can we look into the client's site to check where it went wrong?

**Comment by MansoorAliKhanOfficial** [comment] 2017-06-09 09:39
@tejasm-itpath  The error only occur when you are not login to the site. did you try that?
The version is latest though and when checked WOO was 3.0.7.

**Comment by tejasm-itpath** [comment] 2017-06-09 10:01
Yes, I tried every scenario  @MansoorAliKhanOfficial

**Comment by angelleye** [comment] 2017-06-12 12:47
@MansoorAliKhanOfficial Did you have them disable all other plugins temporarily?

**Comment by MansoorAliKhanOfficial** [comment] 2017-06-12 13:25
Yeah, we did that and you remember we both did testing for this same client and experienced the same issue so reported it.

**Comment by MansoorAliKhanOfficial** [comment] 2017-06-20 05:42
![image](https://user-images.githubusercontent.com/11312949/27318275-022ab3c8-55a5-11e7-9e5d-857fe438eda8.png)
got this again, this time the user loged in is admin.
may be some issue with that?
active plugins
WC vendors
wc vebdors pro 1.4.2
offers for woo
offers for wc vendors

**Comment by tejasm-itpath** [comment] 2017-06-20 05:48
@MansoorAliKhanOfficial 
Check the Ajax response 
Are you getting following response ?
**Null {success:success}**

one of our developer have faced this issue few days ago

**Comment by MansoorAliKhanOfficial** [comment] 2017-06-20 06:00
strange thing is that the offers are showing in the dashbaord

![image](https://user-images.githubusercontent.com/11312949/27318808-a13c89da-55a7-11e7-8455-b706089f6479.png)

**Comment by MansoorAliKhanOfficial** [comment] 2017-06-20 06:11
Also whenever the plugin is active, in firefox console there is some script flooding

![image](https://user-images.githubusercontent.com/11312949/27319095-354e2e5c-55a9-11e7-89d0-7d6742ab206d.png)

**Comment by MansoorAliKhanOfficial** [comment] 2017-06-20 06:37
Also email showing this . this is email sent to the user from admin side /vendor


![image](https://user-images.githubusercontent.com/11312949/27319829-e08784e6-55ac-11e7-8bc9-cd1785b751df.png)

**Comment by tejasm-itpath** [comment] 2017-06-20 06:47
Yes, I will test for the Emails and Null value got at submit offers too
@MansoorAliKhanOfficial

**Comment by tejasm-itpath** [comment] 2017-06-20 07:04
Yes, I will test for the Emails and Null value got at submit offers too
@MansoorAliKhanOfficial

**Comment by tejasm-itpath** [comment] 2017-10-23 13:17
@iMansoorAliKhan  @angelleye  
For now , I have tested above things again.
So current version of Offers for WooCommerce and OFW-Wc-Vendors. 
everything is working perfect. 
Emails + json response of the submit offers. 
I have tested in following themes
- Storefront
- BuddyBoss 4.2.2
- Divi
- Flatsome
- The7
- Vender

**Comment by angelleye** [comment] 2017-11-13 09:03
@iMansoorAliKhan, @tejasm-itpath ran tests and was unable to reproduce this problem.  As such, we're going to close this issue.

**Closed by angelleye** 2017-11-13 09:03 UTC
Labels: Ready for review
