### ISSUE TITLE
Stock validation

### ISSUE THREAD

**Issue by djstallion** [angelleye/offers-for-woocommerce#118] opened 2015-04-01 15:13 UTC
Example: if product have 5 items in stock, customer can make offer for max 5 quantity and can't make offer for 6 or more quantity.

**Comment by kcwebmedia** [comment] 2015-04-01 17:08
IMO would be best to have global setting to 'not allow' offers for more than the 'in stock' amount. Unless product allows backorders.

Currently offer quantity not limited unless it is a product flagged as 'individually purchased'.

**Comment by djstallion** [comment] 2015-04-01 17:14
That option will be nice!

**Comment by angelleye** [comment] 2015-04-01 22:39
@djstallion,

We actually discussed this topic internally as we were building the plugin.  As @kcwebmedia said, we have disabled the ability for people to increase the QTY on "individually purchased" products, but we decided to leave it alone for general products.  

The idea being that even if you only have, say, 10 of an item...if somebody wants to make an offer for 20 or 30 of them you might decide to go ahead and let them buyer know that you can accept their offer, but the additional units will have to be shipped separately (or all units would be delayed until stock arrives.)

This way you can still establish a line of communication with the potential buyer and can also possibly turn the order into a bigger profit which wouldn't have been an opportunity if not for the ability for the buyer to submit such an offer.

Does that make sense?  Do you have any feedback regarding that sort of scenario?

**Comment by djstallion** [comment] 2015-04-06 12:06
Angelleye, your scenario does make sense, but I'm building e-shop with many used single items. With these items I want to able offers only for available stock, because I can't sell these items more.

PS. My english is not good, but hopefully you will understand what I mean.

**Comment by cedarhillgoods** [comment] 2015-04-10 10:06
I'm interested in this as well as my store is entirely composed of one of a kind items emporium style.  Not sure if this is enough to warrant a fork due to differing needs.  I'll try and submit a patch when I understand how the plugin works better.

**Comment by angelleye** [comment] 2015-04-10 10:20
I think we'll probably do what @kcwebmedia is saying.  We could do it based off the "allow backorder" option, and if you are allowing backorders on a product then we could allow offers for more than the "in stock" value, but if you are not allowing backorders then it would only allow offers up to the "in stock" value and nothing greater than that.

Feedback on that sort of an adjustment..??

**Comment by djstallion** [comment] 2015-04-10 10:25
I think that will be a very good solution. By default "allow backorder" not enabled anyway.

**Comment by angelleye** [comment] 2015-04-10 10:35
We're going to be releasing an update here real soon that I'm just about finished testing.  Then this will be included on the following update.

**Comment by cedarhillgoods** [comment] 2015-04-10 10:36
For my purposes yes.  All my items are one of a kind items.

**Comment by cedarhillgoods** [comment] 2015-04-11 05:40
Just to clarify, what is 'individually purchased' product flag referring to?  Do you mean the same thing as  the 'Sold Individually' checkbox on the WooCommerce product page?  I can't find anything that says 'individually purchased'

**Comment by angelleye** [comment] 2015-04-11 06:24
Yes, I'm pretty sure that's what he was referring to.

**Comment by djstallion** [comment] 2015-04-20 14:43
If product is out of stock and "allow backorder" is not enabled, offer button and offer tab is still visible in single product page. This is not a very big issue, but if some customer landing to the out of stock product page he/she can still make an offer.

**Comment by angelleye** [comment] 2015-04-20 18:27
Thanks for the feedback.  We'll get that adjusted.

**Closed** 2015-04-29 09:08 UTC
Labels: enhancement

**Comment by djstallion** [comment] 2015-04-29 09:18
After the last enhancement with plugin activated I got empty admin page.

**Comment by angelleye** [comment] 2015-04-29 09:26
Are you just pulling the dev branch?  I'm working on our current dev branch, which includes this issue update, and I don't seem to be having any issues.

**Comment by djstallion** [comment] 2015-04-29 09:29
Yes, of course the dev branch.

**Comment by angelleye** [comment] 2015-04-29 09:31
Can you enable WP_DEBUG and see if you're getting an actual PHP error or what's going on there?  I'm not having any issues, so it's tough to say what could be going on there.

**Comment by angelleye** [comment] 2015-04-29 09:32
You could have a conflict with some plugin I don't have, for example.

**Comment by djstallion** [comment] 2015-04-29 09:35
Because I'm yet developing my new site, I have WP_DEBUG always enabled. No any PHP errors, just a white and empty admin page. I try to figure out which plugin have conflict.

**Comment by angelleye** [comment] 2015-04-29 09:38
I've noticed that adding this tends to show me more than WP_DEBUG alone:

```
error_reporting(E_ALL|E_STRICT);
ini_set('display_errors', '1');
```

You may want to give that a try and see if you get more info that page.  Generally a blank white page means some sort of PHP error is happening.

**Comment by djstallion** [comment] 2015-04-29 09:40
Adding to where? To the wp-config.php?

**Comment by djstallion** [comment] 2015-04-29 10:29
Unfortunately I got no any PHP errors, just a white admin page. But I disabled all plugins, except WooCommerce and Offers for WooCommerce and all working fine. Then I activated other plugins one by one and Offers for WooCommerce have after this enchancement conflict with Page Builder by SiteOrigin: https://wordpress.org/plugins/siteorigin-panels/
Before this enchancement any previous dev branch have no conflict.

**Comment by angelleye** [comment] 2015-04-29 10:42
Ok, I'll download that plugin and see if I can reproduce the problem.

**Comment by angelleye** [comment] 2015-04-29 10:47
I was able to reproduce the problem after installing and activating that plugin.  I'm not sure why you're not seeing it, but the error happening is a PHP error...

>Fatal error: Call to undefined function get_current_screen() in /home/angelley/sandbox_woocommerce/wp-content/plugins/offers-for-woocommerce/admin/class-offers-for-woocommerce-admin.php on line 818

I'm working now to get it resolved.

**Comment by angelleye** [comment] 2015-04-29 11:11
@djstallion Please check it now.  Should be resolved.

**Comment by djstallion** [comment] 2015-04-29 11:21
I don't know, why I'm not seeing any PHP errors, I try figure it out.

Yes, it is resolved. Conflict is gone and also enchancement works fine. If product is out of stock and "allow backorder" is not enabled, offer button and tab is gone.

Thank you and keep up the good work!

**Comment by angelleye** [comment] 2015-04-29 11:41
Glad to hear it, and we appreciate your feedback on things like this!

**Comment by kcwebmedia** [comment] 2015-04-29 11:43
@djstallion

You are welcome and thank you for your input. As you said, when product 
'out of stock' the form and buttons are not loaded -- In addition the 
max qty allowed on new offer form is also limited by the stock qty on a 
product if that product is currently 'manage stock' and 'do not allow 
backorders' and the offers general setting for stock option is enabled

Furthermore, if you have a variable product, the main 'inventory' tab 
stock qty will take precedence over variant stock qty. You can 
experiment with a variable product with the 'manage stock' checkboxes 
and settings for inventory on variants to get a better idea of how that 
logic is working.

Overall, inventory and stock settings on variants and the parent 
inventory settings must be managed/set correctly. But if a person sets 
up their variant items as 'in stock' and the parent inventory setting is 
'out of stock', then if no backorders allowed you will not get an offer 
form even though the variants allowed it. I hope I have not confused 
you. Let me know if you have questions.

**Comment by djstallion** [comment] 2015-04-29 11:48
I'm glad if I can help You, because you're both developing a very good free plugin. I hope it will be free also in future without any limitations.

@kcwebmedia
I will try this logic if I have more time for this and definitely let you know, If I found some bugs or if I have some thoughts to make this plugin better.

**Comment by angelleye** [comment] 2015-04-29 11:51
There's a possibility we may introduce some premium extensions to this plugin in the future that add additional functionality (for example, syncing eBay offers into this system so that both can be managed from the same screen in WordPress) but the base plugin will always be free, and we will continue to improve and support it.

**Comment by djstallion** [comment] 2015-04-29 11:56
Glad to hear it. Premium extensions are fine, because also you have to be stay alive and buy some food.
Anyway, you got my support and I will help you so much I can.

**Comment by djstallion** [comment] 2015-04-30 12:53
Just for info - I didn't see any PHP errors and one plugin causing this. I don't know how, but it have some conflict with WP_DEBUG, so any debug messages didn't came up anymore. I haven't seen something like this never before.
