### ISSUE TITLE
Individually sold items

### ISSUE THREAD

**Issue by kcwebmedia** [angelleye/offers-for-woocommerce#120] opened 2015-04-02 08:52 UTC
Don't allow admin save offer qty > 1 if product sold individually
* If product is flagged 'sold individually', then show admin warning msg and prevent save as 'accepted' or 'countered' ( QTY must be 1 )

Prevent buyer from add offer to cart on offer that is qty > 1 if product sold individually
* Show buyer error msg
* Trash the offer

**Comment by cedarhillgoods** [comment] 2015-04-11 06:25
Dupe of #118

**Comment by cedarhillgoods** [comment] 2015-04-18 15:07
Should be closed.  Fixed in 1.1.0

**Closed** 2015-04-19 12:13 UTC
Labels: bug
