### ISSUE TITLE
Minimum allowed offer with automatic acceptance [request]

### ISSUE THREAD

**Issue by elarson** [angelleye/offers-for-woocommerce#171] opened 2015-06-21 12:00 UTC
It would be nice if there was the ability to set a minimum allowed offer based on a percentage of the product price that can be automatically accepted. 

Our use case scenario is a donation site for a handicapped artist selling paintings. We do no want to show any prices and want to let the user make a donation offer. We want to be able to accept any donation offer, inculing "0", but we would like it to be automatically accepted if it meets the minimum threshold. This is not meant as a bidding mechanism, but as a way to minimise needing to accept offers.

**Comment by angelleye** [comment] 2015-06-21 19:10
I believe this is related to #35

**Comment by elarson** [comment] 2015-06-22 10:27
Yes, that sounds about right. I'm a bit new to Github for issues, so apologies for not seeing that.

I hope you don't mind all of my requests, and hope this is the right place for posting them. I really like this plugin and we also use your PayPal plugin, and will probably soon use your IPN plugin. You guys do nice work!

**Comment by angelleye** [comment] 2015-06-22 10:30
We appreciate all the feedback.  Keep it coming!  

Glad you like the other plugins you see, too.  Feature requests for any of them can go in their respective GitHub repos.  General support requests could be left on the WordPress directory.

**Comment by angelleye** [comment] 2015-09-26 03:01
Closing this issue because it's a duplicate of #35.

**Closed by angelleye** 2015-09-26 03:01 UTC
Labels: duplicate
